### ISSUE TITLE
sdk 升到了1.5.9就报错了，，本来1.4+是完全没问题的

### ISSUE THREAD

**Issue by hrongyong** [zhangyujiu/wanandroid#2]
Compiler message:
file:///Users/***/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.5.1/lib/cached_network_image.dart:465:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/***/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
Compiler failed on /Users/***/ASFlutterProjects/wanandroid/lib/main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by hrongyong** [comment]
看错了，，本来的是1.2+的

**Comment by zhangyujiu** [comment]
sdk是flutter的还是dart的？flutter建议用最新稳定版，dart建议用2.0+版本

**Comment by zhangyujiu** [comment]
dart的版本是多少，建议升级到最新的
